language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
env:
  global:
  - secure: aqBML17PYvKbZnNN6IgRjSUt8bLFbdQAVMn2TXOQyYAsZuCZ1CUz50F3X3xXmO8gQRXTbbM7zenG7fNhID+PkR0UPc538gu9ecx0qOmtdwZqGEKRvu8ml7InFS4Sl40tsdpl/sEL++jXQMLoSAW4+0h7pmjiTfah4eeNhLqG/8+NcuFSn82Jrd1JyfqpvxxCR27rc8Cc5ED5WYVd8MBcWWlpA0EXtEq2iy//NvqwSAFkcu/JLycQ+5FL2Yl13kJImYFbuXZ51ibrJ8inVauu3LTRIlryilsYT0YMz64GSHZ3CwlaHlKcvFfUNpKgAXGrRksEzeYoWF1MeZfzoyvFayIV091ZWU/tea71QlE5Wow+p+ZpdDTWptZpk7Swzu4DcizGZENEhVjiHnMAYW+tfwG0IvzSvDAVXD2zfixSBYgz1hx1AUwTCn6U+MaSsaK9AuXhdaTxlDQgOecN3ALP+G2VNkLKYhHLHmrxn+6E53IovOAluH5FB5rUwOhZyQXdVVQ6ABT58ENhBL/K1l3t98vzLdYjvW3WykqAdk55HVslnsCbfAsNfzDNv60GZ5pU8xrzWdIY82QWonaVdOsmOZ8/zUZBsG/M0zxl24DeOj0NDvN7GH1CsW5LQBGNA0fou5zuYX1IE/m7BjjOLTUKrMD5DHW9iWhFPjSqq5P6jlM=
  - secure: hxQbwn/YjF8IcXWrE9Iy2ckqFa2q9tn27mK9anE9feW2VD9024y5OeWTSS8D25bISxfzi1/DcSVOSO0PRbZVBDEdM3fpbsCpmz0mhPxHa5dJrTMDimscpIkhIA2t+CwjUQOqW2yfKtg3c459GA74mkaslutdzxq+9ggKbdbzAFanenlFAdJ0hu5/PV6MLCNC8hsAcXWRg+EBNTfJWGaSbXQ1/ha2K4soZ9ZL+3wutFsQfLXcgvCzuoYY/1MjyuA6GTY5hsL3yadVRR01XQyGQkdalYtoKdDLiw467lF2jkL2CCICTvflYHIKdNKZMBrLnFNhi2saq2o+dwIBgxhnkpGWqm2ELzKVXhrYqAYkqEcKhD2GRx6RXC5EEnJX27W85Ap+1fW1unDHyFpFKf5e2t2vDZTzBkbaRuCsmGbeh6OSb5lW0JXFeYQ02IVcGk/TZVw2topA6Vif8/joscvWzf9740nK89uja1SbxIZtUeHJSBfWyquaizVITBrEG/Ul8UhSjFKACohyq+R+ljwYqbNPIYQcHhx//dljfKWzWtaYdqaz2HTnrMfGe4pp4gzDETlhZhkrWRGcMV0QlcWg78lMRX9IRHyrrCbeWqHHx9YeeB727QrkGkqUnJKFdqfuMSaxsPFjojS05CoFWiSwKQEMuiEXZ7mFVUdJDXhkmGU=
