language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG" == "dhis2/pivot-tables-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      mvn clean deploy --settings deploy/settings.xml && exit 0; 
  fi
env:
  global:
  - secure: aqBML17PYvKbZnNN6IgRjSUt8bLFbdQAVMn2TXOQyYAsZuCZ1CUz50F3X3xXmO8gQRXTbbM7zenG7fNhID+PkR0UPc538gu9ecx0qOmtdwZqGEKRvu8ml7InFS4Sl40tsdpl/sEL++jXQMLoSAW4+0h7pmjiTfah4eeNhLqG/8+NcuFSn82Jrd1JyfqpvxxCR27rc8Cc5ED5WYVd8MBcWWlpA0EXtEq2iy//NvqwSAFkcu/JLycQ+5FL2Yl13kJImYFbuXZ51ibrJ8inVauu3LTRIlryilsYT0YMz64GSHZ3CwlaHlKcvFfUNpKgAXGrRksEzeYoWF1MeZfzoyvFayIV091ZWU/tea71QlE5Wow+p+ZpdDTWptZpk7Swzu4DcizGZENEhVjiHnMAYW+tfwG0IvzSvDAVXD2zfixSBYgz1hx1AUwTCn6U+MaSsaK9AuXhdaTxlDQgOecN3ALP+G2VNkLKYhHLHmrxn+6E53IovOAluH5FB5rUwOhZyQXdVVQ6ABT58ENhBL/K1l3t98vzLdYjvW3WykqAdk55HVslnsCbfAsNfzDNv60GZ5pU8xrzWdIY82QWonaVdOsmOZ8/zUZBsG/M0zxl24DeOj0NDvN7GH1CsW5LQBGNA0fou5zuYX1IE/m7BjjOLTUKrMD5DHW9iWhFPjSqq5P6jlM=
  - secure: hxQbwn/YjF8IcXWrE9Iy2ckqFa2q9tn27mK9anE9feW2VD9024y5OeWTSS8D25bISxfzi1/DcSVOSO0PRbZVBDEdM3fpbsCpmz0mhPxHa5dJrTMDimscpIkhIA2t+CwjUQOqW2yfKtg3c459GA74mkaslutdzxq+9ggKbdbzAFanenlFAdJ0hu5/PV6MLCNC8hsAcXWRg+EBNTfJWGaSbXQ1/ha2K4soZ9ZL+3wutFsQfLXcgvCzuoYY/1MjyuA6GTY5hsL3yadVRR01XQyGQkdalYtoKdDLiw467lF2jkL2CCICTvflYHIKdNKZMBrLnFNhi2saq2o+dwIBgxhnkpGWqm2ELzKVXhrYqAYkqEcKhD2GRx6RXC5EEnJX27W85Ap+1fW1unDHyFpFKf5e2t2vDZTzBkbaRuCsmGbeh6OSb5lW0JXFeYQ02IVcGk/TZVw2topA6Vif8/joscvWzf9740nK89uja1SbxIZtUeHJSBfWyquaizVITBrEG/Ul8UhSjFKACohyq+R+ljwYqbNPIYQcHhx//dljfKWzWtaYdqaz2HTnrMfGe4pp4gzDETlhZhkrWRGcMV0QlcWg78lMRX9IRHyrrCbeWqHHx9YeeB727QrkGkqUnJKFdqfuMSaxsPFjojS05CoFWiSwKQEMuiEXZ7mFVUdJDXhkmGU=
notifications:
  slack:
    secure: i+G81ZMo0brh6cS3Z0+XQYSa51nPCctPMjuBhA5btQpTDppb3rwXlrjDzYg7NbWYinBC6EjAn5skwMogkof2k5yotjr3kFkGCER5HYR8aXf5xThC9rDTzkLRg+IaSVurYtILnh68AD/x36Qfm3gTVulB1fhGvtH4ohHa0bGcICo1QOdOd10uEGLT4pdDa8MhOjtcxAV9QAI/Wq3rcF1Ps51o+oIt9lBjqFZh84T0rDTapgV8Eh47rtj4la1kPhWMpGGGqaT/yVc+DgqLCuPc0CbRcchqbJcbAekUE70lVAZBrQ4tbGuSwn+99zXXLV0Tg8Ah92TXfcYibjt7uNdH/PE5SJ/wTWwZz4505kdnKoE6hWbF3Mk2ds5GmYgCLa4R77O8ONVP3YSdjgrNCrjSgQ5ivvbVw+B+p/wxvYJUp3RH/z/ntCowcLmguonWjSo3sIhBiLsM8s6L47A2J1oX3kXDRoKPuCPZj/Dgx1rhA7F39tbW/WCPhN8VKs4KIZaAiwxArPA0niOCym9skn9eZzh3lUvHk6dY/ZogIwBPzdss77mRwnLOCpx6e5tCRi8LpBpjQfnP3y7FL6hIso8b+9Bt9alpyP6bHruGa6wNRRBId1eVpHv2naC49Efth49ahUfue6McBrXj9ZhYRcZrXWHa+Dq+QhzkDZ+j0kyvzmI=
    on_success: change
    on_failure: always
